BBBB BBBB
BBBB BBBBBB

BB BBB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX
                    
                XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                     gettext(u'Rimuovi inserimento') 
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    
BBBBB

BBB BBBB BB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX
            
        XXXXXXXX
    XXXXXX
    BB BBB BBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
             gettext(u'Rimuovi inserimento') 
        XXXXXXXXX
    BBBBB
XXXXXX
BBBBBB

BB BBB BBBBBBBB
    XXXXX
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'Aggiungi inserimento') 
        XXXXXXXXX
    XXXXXX
BBBBB
