XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBB
        XXXXX
            
            
            
            BB BBBBBBBBBBBBBBB
                XXXXX
                    XXX
                        XXXFFFFXXXX
                    XXXX
                XXXXXX
            BBBBB
        XXXXXX
    BBBBBB

    BBBBB BBBBBBBBBBBBBBBB BBBBBBBB

    BBBBB BBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX
    BBBBBBBB BBBBBBBBBBB

    BBBBBBBBBB
XXXXXXX
